Feature users
andrebaltieri/AgendaEventos pull request #103
Opened 2021-06-22 21:33 UTC by phjb

### Status

### Status
READY

### What is it?
CRUD para usuarios

### Why?
Solicitacao do Product Owner

### How?
Criacao do controler UsersController com metodos GET, POST, PUT e DELETE.

Issues #83, #84, #85, #86

2021-06-23 00:42 UTC, renebentes requested changes

2021-06-23 00:45 UTC, phjb commented on Controllers/UsersController.cs
> +        var user = await context.Users.AsNoTracking().FirstOrDefaultAsync();
Sim, ajustei agora

2021-06-23 01:34 UTC, JoaoNascSilva reviewed
Revisões feitas, comentários junto aos pontos em questão.

2021-06-23 01:34 UTC, JoaoNascSilva commented on Controllers/UsersController.cs
> +        [FromServices] DataContext context)
Nos parâmetros de cada método, notei que está sendo usado FromServices, como dito em nossa reunião, não está errado, porém vamos usar a abordagem de injeção de dependência no construtor do controller para mantermos padronizado.

2021-06-23 01:34 UTC, JoaoNascSilva commented on Controllers/UsersController.cs
> +            var roles = await context.Roles.AsNoTracking().ToListAsync();
Nesta consulta de Role quando estiver inserindo, não seria mais válido já consultar pela que esta sendo atribuída na criação do usuário, assim passamos a ter uma consulta com Where, onde pode trazer somente a informada.

2021-06-23 01:34 UTC, JoaoNascSilva commented on Controllers/UsersController.cs
> +        return Ok(users);
Neste ponto sempre será retornado Ok() 'StatusCode - 200'
Seria interessante mudar o retorno para cada situação.

2021-06-23 01:34 UTC, JoaoNascSilva commented on Controllers/UsersController.cs
> +        return Ok(user);
Mesmo caso do método Get anterior.

2021-06-23 01:34 UTC, JoaoNascSilva commented on Controllers/UsersController.cs
> +            return user;
Já aqui não está retornando nenhum status.

2021-06-23 01:34 UTC, JoaoNascSilva commented on Controllers/UsersController.cs
> +            return Ok(user);
Aqui o usuário esta sendo removido, porém sendo retornado no response.

2021-06-23 11:20 UTC, renebentes commented on Controllers/UsersController.cs
> +        return Ok(users);
O que você sugere? Não vejo problema em retornar 200 mesmo com a lista de usuários vazia. Para um retorno único, sim um 404 ficaria melhor.

2021-06-26 19:33 UTC, renebentes approved these changes

2021-06-26 22:19 UTC, JoaoNascSilva approved these changes
Approved

2021-06-27 08:26 UTC, jenrodrigues approved these changes
Approved! \o/

2021-06-28 12:38 UTC, merged

2021-06-28 16:33 UTC, renebentes commented
Closes #83
Closes #84 
Closes #85 
Closes #86